# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='book_info',
            name='book_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='book_purchase_time',
            field=models.DateField(),
        ),
    ]
