# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20161122_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_pwd', models.CharField(max_length=100)),
                ('user_type', models.IntegerField()),
                ('user_alias', models.CharField(max_length=100)),
            ],
        ),
    ]
